/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kTXJJKSnFt1
 */
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { CardContent, Card } from '@/components/ui/card'
import { useState } from 'react'
import Image from 'next/image'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../ui/dialog'
import LoginForm from './LoginForm'
import BidButton from './BidButton'

export function BidPage({ currentBid }) {
  const [bid, setBid] = useState(currentBid + 100000)

  return (
    <div className='w-full max-w-xl mx-auto'>
      <div className='p-4 md:p-6'>
        <div className='grid gap-4'>
          <div className='grid gap-1 mb-2 relative'>
            <h4 className='font-bold text-sm text-center'>Auction Ends In</h4>
            <div className='flex items-center gap-2 justify-center'>
              <div className='font-semibold text-red-500 text-lg'>02:30:45</div>
            </div>
            <div className='absolute right-0'>
              <LoginForm />
            </div>
            <div className='absolute left-0'>
              <img src={'/logo.png'} height={36} width={36} />
            </div>
          </div>
          <div className='flex items-center justify-between'>
            <div className='grid gap-1'>
              <h3 className='text-xl font-bold sm:text-2xl'>
                Sunset on the Seine
              </h3>
              <p className='text-sm font-medium leading-none text-gray-500 dark:text-gray-400'>
                by Claude Monet
              </p>
            </div>
            <div className='text-2xl font-semibold'>
              ₫{currentBid.toLocaleString('en-US')}
            </div>
          </div>
          <div className='grid gap-4'>
            <img
              alt='Artwork'
              className='aspect-[2/1] rounded-lg object-cover border border-gray-200 w-full'
              height={200}
              src='/placeholder.svg'
              width={400}
            />
            <div className='grid gap-4'>
              <div className='grid gap-1'>
                <Label className='text-sm' htmlFor='bid'>
                  Your Bid
                </Label>
                <Input
                  id='bid'
                  min={currentBid + 100000}
                  placeholder='Enter your bid'
                  value={bid.toLocaleString('en-US')}
                  onChange={(e) => {
                    const value = e.target.value.replace(/[^0-9]/g, '')
                    setBid(value)
                  }}
                />
              </div>
              <BidButton />
            </div>
          </div>
          <div className='grid gap-2 my-4'>
            <h4 className='font-bold'>Description</h4>
            <p className='text-sm leading-relaxed md:text-base'>
              Impressionist painting capturing the beauty of the Seine River at
              sunset. Monet's use of color and light creates a serene and dreamy
              atmosphere, drawing the viewer into the scene.
            </p>
          </div>
          <div className='grid gap-2'>
            <h4 className='font-bold'>Artist Details</h4>
            <p className='text-sm leading-relaxed md:text-base'>
              Claude Monet (1840-1926) was a founder of the French Impressionist
              movement. He is renowned for his masterful depictions of light and
              color in landscapes and outdoor scenes.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
